spring:
  shardingsphere:
    datasource:
      names: master
      master:
        jdbcUrl: jdbc:mysql://localhost:3306/mydb?allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&serverTimezone=UTC&useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 1234567
        connectionTimeoutMilliseconds: 3000
        idleTimeoutMilliseconds: 60000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
        minPoolSize: 1
        maintenanceIntervalMilliseconds: 30000

    encrypt:
      tables:
        t_uc_patients:
          columns:
            name:
              plainColumn: name
              cipherColumn: name_cipher
              encryptor: aes_encryptor
            id_no:
              plainColumn: id_no
              cipherColumn: id_no_cipher
              encryptor: aes_encryptor
            mobile:
              plainColumn: mobile
              cipherColumn: mobile_cipher
              encryptor: sha256Random_encryptor
              # 辅助查询列
              assistedQueryColumn: mobile_same_data

      encryptors:
        aes_encryptor:
          type: aes
          props:
            aes.key.value: 123456abc

        sha256_encryptor:
          type: sha256

        sha256Random_encryptor:
          type: SHA256_RANDOM
    props:
      query.with.cipher.column: true

